### ISSUE TITLE
Top Level Domain (TLD) .mini should be changed

### ISSUE THREAD

**Issue by EntropyWorks** [tchughesiv/cf-mini#1]
I would recommend changing your "cf.mini" domain to "cf-mini.example". It appears in your README.md and Dockerfile.

Here is rfc2606 recommendations for TLD's:
  https://tools.ietf.org/html/rfc2606#page-2

The TLD .mini has been delegated to Bayerische Motoren Werke Aktiengesellschaft aka BMW.
   https://www.iana.org/domains/root/db/mini.html

**Comment by tchughesiv** [comment]
done
