### ISSUE TITLE
Cannot staging app in AUFS

### ISSUE THREAD

**Issue by LaynePeng** [tchughesiv/cf-mini#3]
Hi, my env. is docker1.7 with AUFS. After some change, everything work except the app cannot be stage. If you have any solution, please let me know. Warden error logs:

{"timestamp":1436015832.1799314,"message":"spawn (took 0.037906)","log_level":"debug","source":"Warden::Container::Linux","data":{"handle":"18q1hug40hu","request":{"handle":"18q1hug40hu","script":"mkdir -p /app && touch /app/support_heroku_buildpacks && chown -R vcap:vcap /app","privileged":true},"response":{"job_id":2}},"thread_id":69999160709940,"fiber_id":69999160637520,"process_id":6057,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/base.rb","lineno":300,"method":"dispatch"}

{"timestamp":1436015832.2271202,"message":"Exited with status 1 (0.064s): [[\"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/src/closefds/closefds\", \"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/src/closefds/closefds\"], \"/var/vcap/data/warden/depot/18q1hug40hu/bin/iomux-link\", \"-w\", \"/var/vcap/data/warden/depot/18q1hug40hu/jobs/2/cursors\", \"/var/vcap/data/warden/depot/18q1hug40hu/jobs/2\"]","log_level":"warn","source":"Warden::Container::Linux","data":{"handle":"18q1hug40hu","stdout":"","stderr":"mkdir: cannot create directory `/app': Read-only file system\n"},"thread_id":69999160709940,"fiber_id":69999173087100,"process_id":6057,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/spawn.rb","lineno":135,"method":"set_deferred_success"}

**Comment by LaynePeng** [comment]
I have tried:
1. set env when start docker container by "-e HOME=/home/vcap". But nats cannot start;
2. change owner of default HOME /root to vcap:vcap. Not work. 

Hope you can give me some clue.

**Comment by LaynePeng** [comment]
Updated: I tried to use bind_mounts in DEA to mount /app to /app in container with rw. This solved the creating problem, but still cannot work, seem cannot allocate the memory.

**Comment by tchughesiv** [comment]
Layne,
Thanks for your questions. No modifications are required to run the image successfully. Just be sure you meet all requirements as laid out on the docker project page and run according to instructions. At this time, aufs is not a supported storage type. Device mapper works well but be sure to meet all requirements first according to the following link.

https://registry.hub.docker.com/u/tchughesiv/cf-mini/

Once everything is setup accordingly, use this run command to start your container.

docker run --privileged -v /lib/modules:/lib/modules:ro -p 80:80 -p 443:443 -p 4443:4443 -tdi tchughesiv/cf-mini

**Comment by tchughesiv** [comment]
last note... here's the command to run the image

docker run --privileged -v /lib/modules:/lib/modules:ro -p 80:80 -p 443:443 -p 4443:4443 -tdi tchughesiv/cf-mini
