### ISSUE TITLE
Could not run app hello

### ISSUE THREAD

**Issue by miry** [tchughesiv/cf-mini#5]
```
Starting app hello in org DevBox / space dev as admin...
FAILED
Server error, status code: 400, error code: 170001, message: Staging error: failed to stage application:
Failed getting cpu stats: No such file or directory @ rb_sysopen - /tmp/warden/cgroup/cpuacct/instance-18vus7r8i69/cpuacct.usage
```

**Comment by tchughesiv** [comment]
Is your Docker Engine server running with devicemapper storage and sufficient disk space as laid out as one of the requirements?
https://hub.docker.com/r/tchughesiv/cf-mini/
https://github.com/tchughesiv/cf-mini/blob/master/ubuntu15_04.md

When you type "docker info" on your docker engine server, what is the response back?  can you paste that here?

**Comment by tchughesiv** [comment]
also, make sure you're running the container with the recommended parameters... e.g.
'docker run --privileged -v /lib/modules:/lib/modules:ro -p 80:80 -p 443:443 -p 4443:4443 -tdi tchughesiv/cf-mini'

**Comment by miry** [comment]
I use OS X. The boot2docker uses aufs by default. I think the problem that I don't have folder `/lib/modules` on local instance.

```
 $ docker info                     
Containers: 3
Images: 49
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 4
Total Memory: 8.641 GiB
Name: dev
ID: C7FY:YHQX:4Y6I:3NRY:E2PA:JVOR:66AB:YYNJ:W2OJ:OAGI:4YKQ:O4AX
Debug mode (server): true
File Descriptors: 11
Goroutines: 16
System Time: 2015-09-18T06:37:33.90784592Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Username: miry
Registry: https://index.docker.io/v1/
Labels:
 provider=vmwarefusion
```

```
docker@dev:~$ df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                     7.8G    112.3M      7.7G   1% /
tmpfs                     4.3G         0      4.3G   0% /dev/shm
/dev/sda1                37.4G      7.6G     27.9G  21% /mnt/sda1
cgroup                    4.3G         0      4.3G   0% /sys/fs/cgroup
.host:/                 231.3G    187.7G     43.6G  81% /mnt/hgfs
/dev/sda1                37.4G      7.6G     27.9G  21% /mnt/sda1/var/lib/docker/aufs
```

**Comment by tchughesiv** [comment]
I also have a Mac.  If you want to run this locally on your mac, all you have to do is install a virtualization software like VirtualBox which will allow you to run an Ubuntu VM on from your mac, built to the following spec:
https://github.com/tchughesiv/cf-mini/blob/master/ubuntu15_04.md

I've done this and it works great, provided you have the available resources on your mac to run a stack like Cloud Foundry.  Due to the complex nature of the PaaS stack, right now this docker image requires certain storage and access to certain libraries.

**Comment by miry** [comment]
@tchughesiv thanks. I will skip boot2docker stuff.
