### ISSUE TITLE
monit x 2

### ISSUE THREAD

**Issue by Callisto13** [tchughesiv/cf-mini#6]
Hi,
Very cool project! This isn't really an issue, but I was curious about something:
Is there a specific reason why your `run_first.sh` starts all the monit processes, then quits monit, then stops them only to have monit start them up again in `run.sh`? 
Thanks

**Comment by tchughesiv** [comment]
i intend to visit this again, but the issue revolves around initializing the stack and then bringing it back up afterwards.  Doing so stabilizing the database and CF environment for some reason.  I've yet to have time to investigate further.  Tried a lot of things to avoid that restart but so far the stack always fails after 10 minutes or so without it.

**Comment by tchughesiv** [comment]
and thanks!
