### ISSUE TITLE
NATS can't be running success

### ISSUE THREAD

**Issue by wilsonwu** [tchughesiv/cf-mini#8]
Has issue to run cf-min docker image, the hello app instance show 0/1, when change it to 2, show error message, and run the run.sh script in docker container, nats can't be monitoring, please help on this.

**Comment by tchughesiv** [comment]
Wilson, thanks for the feedback!  Have you followed the deployment instructions laid out on the readme page?  This is a complex image/product and certain things are required in order for it to run properly.  Devicemapper storage with udev sync is absolutely critical as is enough container storage and a privileged container on a Host with the proper packages installed.  Read more here:
https://hub.docker.com/r/tchughesiv/cf-mini/
https://github.com/tchughesiv/cf-mini/blob/master/ubuntu15_10.md

If you've done those things i list in the readme, start it with the listed run command, and STILL have issues... I'll definitely dive in further for you.

Let me know... I'll be away from a computer for a few days, so please forgive a delayed response over the weekend.

**Comment by wilsonwu** [comment]
Thanks for your quick response, tried to follow 15_10.md to do the configuration, but docker info no response after setting.
I am running all on an Azure Ubuntu 15.10 and the additional disk is /dev/sdc, size is 50GB, after followed commands and reboot, the current status is docker stop is not working, the vm start very slow.

**Comment by wilsonwu** [comment]
By the way, I am trying to use the default disk 30g (only 27g for me), hope it can works.

**Comment by wilsonwu** [comment]
Still problems, my steps:
1. Create Ubuntu 15.10 and 2 core 7g memory
2. install docker
3. follow your 15_10.md to setup requirement of system
docker daemon -H fd:// -s devicemapper --storage-opt dm.basesize=30G
4. docker info found below:
Storage Driver: devicemapper
Udev Sync Supported: true
PS: I think the system preparation is OK as you said in md
5. pull image and start follow your commands
6. update dns to 176.17.0.2 (login into container and saw the ip)
7. login into container to bash run.sh (got errors)
8. cf login ok
9. create space ok
10. upload a html failed with below error:
tarting app test in org DevBox / space test as admin...
FAILED
Server error, status code: 400, error code: 170001, message: Staging error: failed to stage application:
no connection

also try below:
1. after above 10 steps, restart container
2. run scripts sh files one by one
3. start.sh
Process 'nats_stream_forwarder'     initializing
Process 'etcd'                      initializing
Process 'hm9000_listener'           initializing
Process 'hm9000_fetcher'            initializing
Process 'hm9000_analyzer'           initializing
Process 'hm9000_sender'             initializing
Process 'hm9000_metrics_server'     initializing
Process 'hm9000_api_server'         initializing
Process 'hm9000_evacuator'          initializing
Process 'hm9000_shredder'           initializing
Process 'cloud_controller_ng'       initializing
Process 'cloud_controller_worker_local_1' initializing
Process 'cloud_controller_worker_local_2' initializing
Process 'nginx_cc'                  initializing
Process 'cloud_controller_migration' initializing
Process 'cloud_controller_worker_1' initializing
Process 'cloud_controller_clock'    initializing
Process 'uaa'                       initializing
Process 'haproxy'                   initializing
Process 'gorouter'                  initializing
Process 'warden'                    initializing
Process 'dea_next'                  initializing
Process 'dir_server'                not monitored - start pending
Process 'loggregator_trafficcontroller' not monitored - start pending
Process 'doppler'                   not monitored - start pending
Process 'metron_agent'              not monitored - start pending
Process 'dea_logging_agent'         not monitored - start pending
Process 'etcd_metrics_server'       not monitored - start pending
Process 'route_registrar'           not monitored - start pending
Process 'postgres'                  running - start pending
System 'system_5a5b504e958c'        running - start pending

and reboot the vm, after that:
root@dockercf:~# docker info
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.23/info: read unix @->/var/run/docker.sock: read: connection reset by peer
root@dockercf:~# docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
root@dockercf:~#

DOCKER CAN'T RUN

**Comment by wilsonwu** [comment]
It is running, after create a new vm and run all cmds again, then run scripts/start.sh two times, then change the hello app instance to two, it is working.
