### ISSUE TITLE
Does cf-mini can bind domain?

### ISSUE THREAD

**Issue by wilsonwu** [tchughesiv/cf-mini#9]
I want to run the cf-mini on a public internet, can I bind a domain name? If could, how to do it?

**Comment by tchughesiv** [comment]
Should work just fine.   You'd want to build the cf-mini docker image manually by cloning this repo.  But before building the image, first change the following line in the cf-mini Dockerfile to whatever wildcard DNS domain you own and are pointing at the docker server IP:
ENV NISE_DOMAIN cf-mini.example

**Comment by tchughesiv** [comment]
If this will be publicly accessible, I would probably also advise that you change the default password before the image build is kicked off:
ENV NISE_PASSWORD c1oudc0w

**Comment by tchughesiv** [comment]
although i haven't tested this yet for you, it appears you can override those ENV variables at runtime and that an image rebuild shouldn't be required.  By doing something like the following with the existing image:

```
 docker run --privileged -v /lib/modules:/lib/modules:ro -e "NISE_DOMAIN=new.domain" -e "NISE_PASSWORD=pAsSw0rd" -p 80:80 -p 443:443 -p 4443:4443 -tdi tchughesiv/cf-mini
```

**Comment by wilsonwu** [comment]
Thanks for your quick reply and it is helpful, I will try later and tell you the result.

**Comment by tchughesiv** [comment]
how'd it go wilson?
